import { generateTestId, generateBranchName } from '../helpers/cleanup';

/**
 * Generate test data for E2E tests
 */
export class TestDataGenerator {
  private prefix: string;

  constructor(prefix: string = 'e2e-test') {
    this.prefix = prefix;
  }

  /**
   * Generate a unique test identifier
   */
  generateTestId(): string {
    return generateTestId(this.prefix);
  }

  /**
   * Generate a unique branch name
   */
  generateBranchName(testId?: string): string {
    const id = testId || this.generateTestId();
    return generateBranchName(this.prefix, id);
  }

  /**
   * Generate a PR title
   */
  generatePRTitle(testName: string, testId?: string): string {
    const id = testId || this.generateTestId();
    return `[E2E] ${testName} - ${id}`;
  }

  /**
   * Generate a PR description
   */
  generatePRDescription(testName: string): string {
    return `This is an automated E2E test PR for: ${testName}\n\nCreated by E2E test suite.`;
  }

  /**
   * Generate test file content
   */
  generateFileContent(testId?: string): string {
    const id = testId || this.generateTestId();
    return `# Test File\n\nGenerated by E2E test: ${id}\n\nTimestamp: ${new Date().toISOString()}`;
  }

  /**
   * Generate commit message
   */
  generateCommitMessage(testName: string): string {
    return `[E2E] ${testName} - Test commit`;
  }
}
