name: Bug Report
description: Report a bug or unexpected behavior
title: "[<Category>]: "
labels: ["type: BUG"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill in the required fields below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Example: When I click the submit button, nothing happens...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Example: The form should submit and show a success message
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Information about your environment (optional but recommended)
      placeholder: Example: Windows 11, Chrome 120, Version 1.2.3
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Additional Information (Optional)
        The fields below are optional but help our QA team provide more comprehensive bug documentation.

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does this bug occur?
      options:
        - Always
        - Sometimes
        - Rarely
        - Once
      default: 0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Any relevant console errors, stack traces, or log output
      placeholder: |
        Paste logs or error messages here...
        Example:
        ```
        Error: Cannot read property 'x' of undefined
            at Component.handleClick (app.js:123)
        ```
      render: shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Screenshots/Videos**: If applicable, please drag and drop screenshots or videos here to help explain the problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, information, or observations about the bug
      placeholder: This happens after updating to the latest version...
    validations:
      required: false
