name: 📜 Feature/Enhancement Request 📜
description: Want to see something new in the product? Want to see any adjustment to what's already there? Articulate it here!
title: "< Put Title Here >"
type: "Feature"
body:
- type: markdown
  attributes:
    value: |
          Please fill out the sections below to help us understand and evaluate your request. Issues missing detail may be returned for clarification.
- type: textarea
  id: problem
  attributes:
    label: Problem Statement / Background
    description: |
      Focus on the "why" - not the solution, yet.
      - What problem is being solved?
      - Why is this needed (user friction, business impact, etc.)
      - Link to any user feedback/research or related tickets, if relevant
    placeholder: A clear definition of 'why' will help contextualize discussions and influence solutions.
  validations:
    required: true
- type: textarea
  id: goals
  attributes:
    label: Goals / Outcomes
    description: |
      - What are the expected outcomes of this feature?
      - How do we know it's successful?
    placeholder: Knowing what the end goal is and how to evaluate success makes planning out implementation easier.
  validations:
    required: true
- type: textarea
  id: proposed_solution
  attributes:
    label: Proposed Solution
    description: |
      - What are we building/modifying? 
      - Include scope boundaries, interactsion, and business logic.
    placeholder: Though not guaranteed to be the implemented solution - this helps provide context.
  validations:
    required: true
- type: input
  id: tag
  attributes:
    label: Issue Marker
    value: 📜 Feature/Enhancement Request 📜
    description: DO NOT EDIT – used by automation.
  validations:
    required: false