name: 📜 Feature Request 📜
description: Want to see something new in the product? Want to see any adjustment to what's already there? Articulate it here!
title: "< Put Title Here >"
type: "Feature"
labels:
body:
- type: markdown
  id: feature_request
  attributes:
    value: |
    # 📜 Feature Request 📜
     Want to see something new in the product? Want to see any adjustment to what's already there? Articulate it here!
- type: textarea
  id: problem
  attributes:
    label: Problem Statement / Background
    description: |
      Focus on the "why" - not the solution, yet.
      - What problem is being solved?
      - Why is this needed (user friction, business impact, etc.)
      - Link to any user feedback/research or related tickets, if relevant
    placeholder: A clear definition of 'why' will help contextualize discussions and influence solutions.
  validations:
    required: true
- type: textarea
  id: goals
  attributes:
    label: Goals / Outcomes
    description: |
      - What are the expected outcomes of this feature?
      - How do we know it's successful?
    placeholder: Knowing what the end goal is and how to evaluate success makes planning out implementation easier.
  validations:
    required: true
- type: textarea
  id: proposed_solution
  attributes:
    label: Proposed Solution
    description: |
      - What are we building/modifying? 
      - Include scope boundaries, interactsion, and business logic.
    placeholder: Though not guaranteed to be the implemented solution - this helps provide context.
  validations:
    required: true
- type: textarea
  id: criteria
  attributes:
    label: Acceptence Criteria
    description: |
      - Define "done" in clear and testable terms
      - Consider all relevant angles (e.g., product impact, user experience, implementation, testing, etc.)
    placeholder: Though not guaranteed to be the implemented solution - this helps provide context.
  validations:
    required: true
- type: textarea
  id: artifacts
  attributes:
    label: Design Artifacts / References
    description: |
      Link to relevant user flows/designs in Figma, spec documents in Google Drive, etc. Clarify whether they are finalized/approved or WIP.
    placeholder: Insert links or files here.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
       ## Optional Information
       Though not required, providing more information below gives a more complete picture of what is being asked for (and will generally lead to a quicker turn around time).
- type: dropdown
  id: priority
  attributes:
    label: Priority
    description: (Optional) How time-sensitive is this work?
    options:
      - 🔴 P0
      - 🔶 P1
      - 🟡 P2
      - 🟢 P3
      - ⚪ P4
    validations:
      required: false
- type: dropdown
  id: impact
  attributes:
    label: Impact Level
    description: Who or what is affected, and how significantly?
    options:
      - 🔴 Critical
      - 🔶 High
      - 🟡 Medium
      - 🟢 Low
      - ⚪ Unknown
- type: textarea
  id: constraints
  attributes:
    label: Constraints
    description: |
      (Optional) Mitigates feature creep and misaligned assumptions
      - Outline what this feature isn't aiming to resolve/cover
    placeholder: This feature will NOT include ...
  validations:
    required: false
- type: textarea
  id: dependencies
  attributes:
    label: Dependencies
    description: |
      (Optional) Highlight dependencies to be aware of to improve understanding / visibility
      - Link related issues, features, 3rd-party dependencies
    placeholder: This feature depends on ...
  validations:
    required: false