name: "Post Issue/PR Comment"
description: "Create a comment on an issue or PR"
inputs:
  body:
    description: "Markdown body of the comment"
    required: true
  token:
    description: "GitHub token with issues:write"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Post comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const isIssue = !!context.payload.issue;
          const number = (isIssue ? context.payload.issue : context.payload.pull_request).number;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: number,
            body: process.env.BODY
          });
      env:
        BODY: ${{ inputs.body }}
