name: "Manage Assignees"
description: "Add or remove assignees on an issue or PR"
inputs:
  action:
    description: "add | remove"
    required: true
  assignees:
    description: 'JSON array of usernames, e.g. ["octocat"]'
    required: true
  token:
    description: "GitHub token with issues:write"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Apply assignee changes
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { context, github, core } = require('@actions/github');
          const number = (context.payload.issue || context.payload.pull_request).number;
          const owner = context.repo.owner;
          const repo  = context.repo.repo;
          const action = process.env.ACTION;
          const assignees = JSON.parse(process.env.ASSIGNEES);

          core.info(`${action} assignees: ${assignees.join(", ")}`);

          if (action === 'add') {
            await github.rest.issues.addAssignees({ owner, repo, issue_number: number, assignees });
          } else if (action === 'remove') {
            await github.rest.issues.removeAssignees({ owner, repo, issue_number: number, assignees });
          } else {
            core.setFailed(`Unsupported action: ${action}`);
          }
      env:
        ACTION: ${{ inputs.action }}
        ASSIGNEES: ${{ inputs.assignees }}
