name: Auto-Close PRs Unless Author Has Write Access

on:
  pull_request:
    types: [opened]

jobs:
  close-unapproved-prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      # Needed to read permissions of collaborators

    steps:
      - name: Check author permission and conditionally close
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prAuthor = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;

            const permissionResp = await github.rest.repos.getCollaboratorPermissionLevel({
              owner,
              repo,
              username: prAuthor
            });

            const permission = permissionResp.data.permission;
            const approvedPermissions = ['admin', 'write', 'maintain'];

            if (!approvedPermissions.includes(permission)) {
              await github.issues.createComment({
                issue_number: prNumber,
                owner,
                repo,
                body: `Howdy @${prAuthor}, this repository does not accept pull requests from users without write access. Closing this PR.`
              });

              await github.pulls.update({
                pull_number: prNumber,
                owner,
                repo,
                state: 'closed'
              });
            } else {
              console.log(`User ${prAuthor} has ${permission} permission. PR allowed.`);
            }
