name: Manage Assignees
"on":
  workflow_call:
    inputs:
      action:
        required: true
        type: string  # "add" | "remove"
      assignees:
        required: true
        type: string  # JSON array string, e.g. ["octocat"]
    secrets:
      token:
        required: true

permissions:
  issues: write
  contents: read

jobs:
  assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.token }}
          script: |
            const number = (context.payload.issue ?? context.payload.pull_request).number;
            const action = `${{ inputs.action }}`;
            const assignees = JSON.parse(`${{ inputs.assignees }}`);
            if (action === 'add') {
              await github.rest.issues.addAssignees({ owner: context.repo.owner, repo: context.repo.repo, issue_number: number, assignees });
            } else {
              await github.rest.issues.removeAssignees({ owner: context.repo.owner, repo: context.repo.repo, issue_number: number, assignees });
            }
