name: Manage Labels
"on":
  workflow_call:
    inputs:
      add:
        required: false
        type: string   # JSON array string, e.g. ["needs-triage"]
        default: "[]"
      remove:
        required: false
        type: string
        default: "[]"
    secrets:
      token:
        required: true

permissions:
  issues: write
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.token }}
          script: |
            const num = (context.payload.issue ?? context.payload.pull_request).number;
            const add = JSON.parse(`${{ inputs.add }}`);
            const remove = JSON.parse(`${{ inputs.remove }}`);
            if (add.length) {
              await github.rest.issues.addLabels({ owner: context.repo.owner, repo: context.repo.repo, issue_number: num, labels: add });
            }
            for (const name of remove) {
              try {
                await github.rest.issues.removeLabel({ owner: context.repo.owner, repo: context.repo.repo, issue_number: num, name });
              } catch { /* ignore if not present */ }
            }
